name: BloqGo CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: Cross-compile
        run: |
          mkdir -p dist
          GOOS=linux   GOARCH=amd64 go build -o dist/bloqgo-linux-amd64   .
          GOOS=windows GOARCH=amd64 go build -o dist/bloqgo-windows-amd64.exe .
          GOOS=darwin  GOARCH=amd64 go build -o dist/bloqgo-darwin-amd64  .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bloqgo-binaries
          path: dist/